const puppeteer = require('puppeteer');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const RUNDOWN_FILE = path.join(__dirname, 'game', 'v5', 'final_rundown.md');
const WHATSAPP_MESSAGES_FILE = path.join(__dirname, 'game', 'v5', 'whatsapp_pack', 'all_player_messages.md');

const TEAM_DRESSCODES = {
  'Startup Investors': 'Patagonia Vests & Finance Bro Chic',
  'Product Council': 'Turtlenecks & Visionary Core',
  'Engineering Blackbox': 'Dark Mode & Hackathon Hoodies',
  'Ops & Ground Truth': 'Tactical Execution Wear',
  'Culture & Narrative Lab': 'Pretentious Creatives',
  'Culture & Narrative/Media': 'Pretentious Creatives'
};

const TEAM_COLORS = {
  'Startup Investors': '#4CAF50',
  'Product Council': '#2196F3',
  'Engineering Blackbox': '#9C27B0',
  'Ops & Ground Truth': '#FF9800',
  'Culture & Narrative Lab': '#E91E63',
  'Culture & Narrative/Media': '#E91E63'
};

const TEAM_SUMMARIES = {
  'Startup Investors': 'Hold the cap table and the leverage. Looking for scapegoats to save their portfolio.',
  'Product Council': 'Wrote the roadmaps that failed. Trying to blame Engineering for the technical collapse.',
  'Engineering Blackbox': 'Ignored security flaws to force the launch. Trying to blame Product\'s impossible deadlines.',
  'Ops & Ground Truth': 'Hold the physical timeline of V\'s death. Trying to catch the other teams in lies.',
  'Culture & Narrative Lab': 'Spun the failure into a success story. Trying to figure out who gave them the fake data.'
};

const CHARACTER_QUIRKS = [
  "Speaks entirely in corporate buzzwords (synergy, bandwidth, pivot).",
  "Adjusts glasses/hair dramatically before dropping any evidence.",
  "Always acts like they are late for a very important Zoom meeting.",
  "Refuses to make eye contact when talking about the timeline.",
  "Constantly checks their crypto wallet on their phone during conversations.",
  "Takes physical notes on a notepad when other people speak.",
  "Interrupts people to correct their grammar or technical terminology.",
  "Speaks slightly too loud, as if pitching everything to an investor.",
  "Acts extremely paranoid, looking over their shoulder before sharing clues.",
  "Drops names of fake startup founders to sound important.",
  "Overly enthusiastic about 'the mission' despite the company collapsing.",
  "Pretends to know everything about AI, but clearly has no idea."
];

const EVIDENCE_CONTEXT = {
  'prod-deploy-log-7:03.txt': 'CONTEXT: This log proves the 19:03 shadow deploy was a deliberate override by Anubhav, Devashish, and Kovid, excluding the founder from the process.',
  'auth-vuln-P0-jira.pdf': 'CONTEXT: This report shows Engineering knew the system was broken before launch. Harsh ignored the leak at 18:50 under pressure from Neil.',
  'cease-desist-draft.pdf': 'CONTEXT: This document proves the board was prepared to legally erase V even before the accident happened. Drafted by Akshat and Devashish.',
  'inboard-notes-v-edit.pdf': 'CONTEXT: These redacted notes show the timeline of the "Silent Hour" where the security door was locked by Iti and Shaunak.',
  'treasury-map-Nov.xlsx': 'CONTEXT: This file reveals the emergency media payouts authorized by Sarthak and Aniket to cover up the death.',
  'ab-test-raw-export.csv': 'CONTEXT: This data proves the launch was a total failure, despite the "Success" press release.',
  'side-letter-v2-signed.pdf': 'CONTEXT: The illegal contract that gave investors a "Kill-Switch" over the founder. Signed by Siddak and Mehul.',
  'voice-clone-founder.m4a': 'CONTEXT: A hidden recording showing that the "Farewell Audio" from V was actually a clone generated by Pranjal.',
  'grove-commentary-gen-v4.txt': 'CONTEXT: The raw prompts used by the Narrative Lab to generate thousands of fake positive reviews for the broken launch.'
};

const PERSONAL_MEMORIES = {
  // CLUSTER 1: THE ARCHITECTS (Serial B Pressure)
  'Siddak Bakshi': "PERSONAL MEMORY: At 18:55 PM, you physically slammed the door to the executive suite and told V, 'Launch it or lose your seat.' You knew the 19:03 Shadow Deploy was a fraud, but you needed the valuation to spike. You ignored the rising heat-sensors on your phone dashboard while Akshat stood by.",
  'Mehul Mohan': "PERSONAL MEMORY: You were the one who told the Product Council, 'I do not care if the code is burning.' You watched the Shadow Deploy trigger at 19:03 PM and celebrated with champagne. You shared the moment with Vishnupriya, who later saw you delete a panicked message from V.",
  'Akshat': "PERSONAL MEMORY: You drafted the side-letter at 17:55 PM. At 18:55, you stood behind Siddak as he threatened V. You told the Product Council that if they failed the 19:00 launch, you would bankrupt the company personally.",
  'Aniket Chandra': "PERSONAL MEMORY: You saw the 'Emergency Fund' being drained at 18:30 PM to pay for the media blackout. You looked at Sagar and gave him the green light to leak the fake metrics. You knew V was being erased from the ledger before he was even dead.",
  'Sarthak': "PERSONAL MEMORY: You authorized the 'Emergency Liquidity' transfer at 18:45 PM. You saw V's desperate Slack message asking to stop the launch, but you muted the notification. You knew this money was for the aftermath cleanup.",

  // CLUSTER 2: THE EXECUTIONERS (Shadow Deploy Team)
  'Anubhav Gaba': "PERSONAL MEMORY: At 19:03 PM, you hit 'EXECUTE' on the V3-Shadow branch alongside Devashish and Kovid. You saw V's panicked face through the server room glass at 20:15 PM and you turned your back, leaving Vaibhav to monitor the mounting errors.",
  'Devashish Rane': "PERSONAL MEMORY: You co-signed the deployment keys at 19:03 PM. You knew the Version 3 patch was a lie. Later, at 20:30 PM, you drafted the final Cease and Desist to prove V was 'insubordinate' while he was still trapped in SR-4.",
  'Kovid Poudel': "PERSONAL MEMORY: Your hands were shaking at 19:03 PM as you authorized the Shadow Deploy. Later, at 21:05 PM, you triggered the remote server purge to wipe the logs. You intentionally ignored the 'Zone 4 Occupied' flag.",
  'Vaibhav Gupta': "PERSONAL MEMORY: You saw the 'Failover Loop' at 19:05 PM but didn't report it. You saw Anubhav leave the floor and you said nothing. You watched Shubham Jain manually disable the alarms later that hour.",

  // CLUSTER 3: THE SILENCERS (Trapping V)
  'Iti Kathed': "PERSONAL MEMORY: At 20:15 PM, you watched V walk into Server Room 4. Shaunak was right next to you. You locked the heavy magnetic security door from the outside to 'prevent a scene' until the launch was confirmed. You told Mammoth to take a break.",
  'Shaunak': "PERSONAL MEMORY: You watched Iti lock the SR-4 door. You heard the muffled shouting from V for ten minutes. You looked at the camera feed and saw him struggling with the internal vent, then you turned the monitor off so no one else would see.",
  'Adarsh': "PERSONAL MEMORY: You were at the security gate at 20:15 PM. You saw V walk in and then saw Iti click the lock. You thought it was a prank. You joked with Ayush Borse about 'the founder finally getting some quiet time'.",
  'Mammoth': "PERSONAL MEMORY: You were the physical security lead. You were told by Iti to 'take a break' at 20:10 PM. When you came back at 21:14, the power was back on and a body was on the floor. You realized you were moved out of the way.",

  // CLUSTER 4: THE REVOKERS (Access Denial)
  'Shikhar Sharma': "PERSONAL MEMORY: At 21:00 PM, you and Ayush Mittal shared the root terminal. You clicked 'REVOKE ALL' on V's executive keycard while he was still inside Room 4. You set the Shadow Deploy script to self-destruct. You saw Swapnil distracting V's family on the phone.",
  'Ayush Mittal': "PERSONAL MEMORY: You gave the root credentials to Shikhar. At 21:00 PM, you watched him deactivate V's emergency exit privileges. You heard the magnetic lock click into 'Permanent Seal' mode and you did nothing to help him.",

  // CLUSTER 5: THE ERASERS (Power Cycle)
  'Naisargi Kothari': "PERSONAL MEMORY: At 21:03 PM, you initiated the 'Full System Power Cycle' with Bharat and Pooja. You heard a metallic thud from the vents. You didn't realize the power-cycle also disabled the emergency oxygen scrubbers. Shrenik was monitoring the board.",
  'Bharat Dhir': "PERSONAL MEMORY: You were there when Naisargi triggered the power-cycle. You found V's body at 21:14 PM. The air in SR-4 tasted like ozone. You were told by Pooja to 'Clean it up' and hide the manual repair kit V was using.",
  'Pooja Ghatia': "PERSONAL MEMORY: You authorized Naisargi to cycle the power. When Bharat found the body, you ordered the floor-wipe and told everyone to stick to the 'Technical Malfunction' story or lose their payouts.",
  'Shrenik Golecha': "PERSONAL MEMORY: You were in Ops when the power-cycle happened. You heard the ventilation fans die. You looked at Vihan and realized V was still in there, but you said nothing to help. You saw Naisargi hit the switch.",
  'Vihan': "PERSONAL MEMORY: You saw the 'Zone 4 Lock' engage at 21:03. You heard the systems fail. You didn't override it because Shrenik told you it was a 'Security protocol'. You saw Bharat enter the room 10 minutes later and scream.",

  // CLUSTER 6: NARRATIVE CONTROL
  'Rahul': "PERSONAL MEMORY: At 19:15 PM, you were told the metrics were fake. You wrote the press release celebrating the 'record-breaking launch' anyway. You saw Varun drafting the 'founder's exit statement' while V was still alive.",
  'Varun Chopra': "PERSONAL MEMORY: You drafted the 'Technical Malfunction' script at 21:20 PM. You used the exact wording Pooja gave you. You helped Rahul polish the fake metrics report while the ambulance was arriving.",
  'Sagar Badiyani': "PERSONAL MEMORY: You leaked the 'Record Breaking Metrics' at 19:10 PM. You knew the code was broken, but you wanted the glory. You saw V waving frantically from the server room glass at 20:30 and you just kept walking.",
  'Aiswarya Mahajan': "PERSONAL MEMORY: You spent the evening drafting fake testimonials to drown out the negative press. You saw Pranjal Srivastava editing the security footage to remove the frames where the SR-4 door was locked.",
  'Pranjal Srivastava': "PERSONAL MEMORY: You edited the live-stream footage to remove the sparks from the server racks. You also deleted the 10-minute gap of security footage showing Iti and Shaunak at the SR-4 door.",

  // CLUSTER 7: THE AUDITORS (Hidden Truths)
  'Aanak Sengupta': "PERSONAL MEMORY: You found the discrepancy in the 'Version 3' checksums at 19:20 PM. You tried to alert the Product Council, but your access was restricted. You shared a backup of the error log with Ritvik.",
  'Ritvik Hedge': "PERSONAL MEMORY: You saw the emails from V at 18:35 PM titled 'THEY ARE KILLING THE CORE'. You kept a local copy on a USB drive. You know the truth is in the side-letter Harsh was carrying before he left.",
  'Shubh Khandelwal': "PERSONAL MEMORY: You noticed that V's calendar had been wiped at 18:00 PM. You realized they were erasing him long before he was trapped. You saw Kartik hiding the OOM-RACE errors on the main dashboard.",
  'Kartik Khandelwal': "PERSONAL MEMORY: You assigned the 'Version 3' label to the broken code. You saw the OOM-RACE errors at 20:58 PM and hid them from the log. You were too afraid of Akshat to speak up.",
  'Harsh Bhimrajka': "PERSONAL MEMORY: You saw the memory leak at 18:50 PM. Neil told you to leave. You saved your work and left at 19:00 PM, choosing your flight over the P0 fix that eventually caused the heat-spike.",
  'Neil Daftary': "PERSONAL MEMORY: You provided the 'kill-switch' justification used to lock V in. You saw the memory leak warnings and told Harsh to ignore them, knowing the overheat would wipe the physical drives.",

  // CLUSTER 8: WITNESSES
  'Manasi Chansoria': "PERSONAL MEMORY: You saw the temperature in SR-4 hit 114°F at 20:45 PM. You tried to call V, but the lines were cut. You saw Mohnish Mhatre watching the same dashboard in terrified silence.",
  'Mohnish Mhatre': "PERSONAL MEMORY: You saw the 'Log-Wipe-Successful' notification at 21:10 PM. You looked at Manasi and realized she saw the temperature spike too. You both agreed to say nothing to Pooja.",
  'Gunjan Samtani': "PERSONAL MEMORY: At 21:03, you physically stopped a colleague from re-enabling the oxygen scrubbers, claiming it would 'short the whole rack'. You watched the clock while the air ran out.",
  'Vishnupriya': "PERSONAL MEMORY: You saw Mehul Mohan checking his phone nervously at 19:03 PM. Later, you saw him delete a message thread from the Product Council. You are the only one who knows the Investors ordered it.",
  'Surabhi Solanki': "PERSONAL MEMORY: You walked onto the engineering floor at 19:03 PM and saw Shubham Jain unplugging a warning siren. You hold the original notes showing the exact second the oxygen failed in SR-4.",
  'Shubham Jain': "PERSONAL MEMORY: At 19:05 PM, you manually disabled the building's haptic alarm floor-grid for Zone 4. You didn't want the investors to hear the failure sirens. You saw the 'OXYGEN WARNING' and clicked 'Dismiss'.",
  'Ayush Borse': "PERSONAL MEMORY: You were in the lobby keeping investors happy. You heard the muffled thumps from SR-4 at 20:50 PM and you turned up the music. You saw Swapnil nod to you during the loudest thump.",
  'Swapnil': "PERSONAL MEMORY: You distracted V's family on the phone at 21:00 PM. You heard them asking if he was coming home for cake. You saw Ayush Borse watching you through the glass.",

  // LATE COMERS (Simplified Roles)
  'Prachi Verma': "PERSONAL MEMORY: You arrived late at 21:20 PM. You saw the cleaning crew scrubbing the SR-4 floor in a hurry. You found a broken fingernail near the door but didn't know what it meant.",
  'Abhishek Gosavi': "PERSONAL MEMORY: You arrived late at 21:25 PM. You found a deleted 'P0-CRITICAL' Jira ticket on V's terminal and restored it to a hidden folder, wondering why it was erased.",
  'Abhishek Mukharjee': "PERSONAL MEMORY: You arrived at 21:30 PM. You saw Rahul and Varun whispering near the exit. You were asked to handle the 'Technical Issue' boilerplate response for the forum.",
  'Vrishali': "PERSONAL MEMORY: You arrived at 21:15 PM. You saw Bharat Dhir coming out of SR-4 looking pale. He told you the room was 'off-limits for maintenance' and you didn't question it."
};

const ORIGINAL_CODES = {
  "Aanak Sengupta": "48335",
  "Abhishek Gosavi": "47092",
  "Abhishek Mukharjee": "89777",
  "Adarsh": "17013",
  "Aiswarya Mahajan": "32859",
  "Akshat": "89225",
  "Aniket Chandra": "35235",
  "Anubhav Gaba": "13025",
  "Ayush Borse": "28895",
  "Ayush Mittal": "92970",
  "Bharat Dhir": "80022",
  "Devashish Rane": "38037",
  "Gunjan Samtani": "21699",
  "Harsh Bhimrajka": "32705",
  "Iti Kathed": "38503",
  "Kartik Khandelwal": "74965",
  "Kovid Poudel": "26744",
  "Mammoth": "53320",
  "Manasi Chansoria": "74911",
  "Mehul Mohan": "23748",
  "Mohnish Mhatre": "69300",
  "Naisargi Kothari": "79863",
  "Neil Daftary": "67535",
  "Pooja Ghatia": "98180",
  "Prachi Verma": "72589",
  "Pranjal Srivastava": "18038",
  "Rahul": "75322",
  "Ritvik Hedge": "31678",
  "Sagar Badiyani": "33633",
  "Shaunak": "72497",
  "Shikhar Sharma": "90111",
  "Shrenik Golecha": "49857",
  "Shubh Khandelwal": "20086",
  "Shubham Jain": "53767",
  "Siddak Bakshi": "24842",
  "Surabhi Solanki": "94326",
  "Swapnil": "47931",
  "Vaibhav Gupta": "48090",
  "Vihan": "22222",
  "Varun Chopra": "34091",
  "Vishnupriya": "58497",
  "Vrishali": "32306",
  "Sarthak": "11111"
};

const DEFAULT_MEMORIES_BY_TEAM = {
  'Product Council': "PERSONAL MEMORY: You saw the Product roadmap being rewritten at the last second. You knew the Version 3 release was unstable, but you didn't see the Shadow Deploy happen.",
  'Engineering Blackbox': "PERSONAL MEMORY: You were debugging the core when the power-cycle hit. You felt the ventilation stop, but you thought it was a test. You didn't know V was in SR-4.",
  'Startup Investors': "PERSONAL MEMORY: You were pressuring the board for a valuation spike. You didn't care about the engineering risks, as long as the dashboard stayed green for the demo.",
  'Ops & Ground Truth': "PERSONAL MEMORY: You saw the floor-grid alarms being disabled, but you were told it was for visitor safety. You realized too late that the emergency oxygen was linked to that grid.",
  'Culture & Narrative Lab': "PERSONAL MEMORY: You were drafting the success story while the sirens were muted. You didn't realize the 'technical malfunction' was actually a person dying in the next room."
};

function extractWhatsAppDetails() {
  const rawText = fs.readFileSync(WHATSAPP_MESSAGES_FILE, 'utf-8');
  const sections = rawText.split('## ');
  const dict = {};

  sections.forEach(section => {
    if (!section.trim()) return;
    const lines = section.split('\n');
    const name = lines[0].trim();

    let profile = '';
    let mission = '';
    let evidence = '';

    lines.forEach(line => {
      if (line.includes('- Public profile:')) profile = line.split('- Public profile:')[1].trim();
      if (line.includes('- Live mission:')) mission = line.split('- Live mission:')[1].trim();
      if (line.includes('- Evidence lane:')) evidence = line.split('- Evidence lane:')[1].trim();
    });

    dict[name] = { profile, mission, evidence };
  });
  return dict;
}

async function generateHTMLPosters() {
  const markdown = fs.readFileSync(RUNDOWN_FILE, 'utf-8');
  const detailsDict = extractWhatsAppDetails();

  const lines = markdown.split('\n');
  const guests = [];

  let inTable = false;
  for (const line of lines) {
    if (line.includes('| Name | Team |')) {
      inTable = true;
      continue;
    }
    if (inTable && line.startsWith('|---')) continue;
    if (inTable && line.startsWith('|')) {
      const parts = line.split('|').map(s => s.trim()).filter(s => s);
      if (parts.length >= 4 && parts[0] !== 'Name') {
        const name = parts[0];
        const data = detailsDict[name] || {};

        let evidenceFile = data.evidence || parts[3] || '';
        let finalClue = evidenceFile ? 'You hold the access to: ' + evidenceFile : 'No physical evidence provided. Rely on your testimony.';
        if (evidenceFile && EVIDENCE_CONTEXT[evidenceFile]) {
          finalClue += '\n\n' + EVIDENCE_CONTEXT[evidenceFile];
        }

        let guestMemory = PERSONAL_MEMORIES[name] || DEFAULT_MEMORIES_BY_TEAM[parts[1]] || "PERSONAL MEMORY: You were present in the building when V died, but you chose to stay completely silent.";

        guests.push({
          name: name,
          team: parts[1],
          role: parts[1] + ' Representative',
          mission: data.mission || 'Find out who locked the door to Server Room 4 at 20:15 PM.',
          quirk: CHARACTER_QUIRKS[Math.floor(Math.random() * CHARACTER_QUIRKS.length)],
          profile: data.profile || 'Standard employee profile.',
          clue: finalClue,
          memory: guestMemory
        });
      }
    }
  }

  // Inject Vishnupriya
  if (!guests.some(g => g.name === 'Vishnupriya')) {
    guests.push({
      name: 'Vishnupriya',
      team: 'Startup Investors',
      role: "The Founder's Plus-One",
      mission: 'Convince two strangers that Mehul is completely innocent before Round 2.',
      quirk: 'Defends Mehul aggressively, even when no one is attacking him.',
      profile: 'Partner to the Tech founder. Trusts him completely minus one small detail.',
      clue: 'Clue: "I saw Mehul checking his phone nervously at 19:03 PM. What happened at 19:03?"\n\nCONTEXT: This testimony proves that someone in the Investor team was aware of unfolding events.',
      memory: PERSONAL_MEMORIES['Vishnupriya']
    });
  }

  // Inject Surabhi Solanki
  if (!guests.some(g => g.name === 'Surabhi Solanki')) {
    guests.push({
      name: 'Surabhi Solanki',
      team: 'Engineering Blackbox',
      role: "The Data Scientist's Plus-One",
      mission: 'Defend Shubham\'s data models to everyone you meet.',
      quirk: 'Gasps dramatically whenever someone mentions a database crash.',
      profile: 'Partner to Shubham Jain. Knows exactly how many hours he spent building the performance model.',
      clue: 'Clue: "Shubham told me his model was perfect, but Product forced him to change the outputs."\n\nCONTEXT: This proves pressure to falsify data.',
      memory: PERSONAL_MEMORIES['Surabhi Solanki']
    });
  }

  // Generate the company map HTML block
  let rosterHTML = '';
  const groupedGuests = {};
  guests.forEach(g => {
    if (!groupedGuests[g.team]) groupedGuests[g.team] = [];
    groupedGuests[g.team].push(g);
  });

  for (const [team, members] of Object.entries(groupedGuests)) {
    rosterHTML += `<div class="team-block" style="border-left: 4px solid ${TEAM_COLORS[team] || '#fff'}; padding-left: 20px; margin-bottom: 30px;">`;
    rosterHTML += `<h3 style="color: ${TEAM_COLORS[team] || '#fff'}; margin-top: 0; font-size: 26px;">${team}</h3>`;
    members.forEach(m => {
      rosterHTML += `<p style="margin: 5px 0; font-size: 20px;"><strong>${m.name}</strong> - <span style="color: #A39B8A">${m.role.split('-')[0].trim()}</span></p>`;
    });
    rosterHTML += `</div>`;
  }

  const outDir = path.join(__dirname, 'ultimate_posters');
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir);

  const browser = await puppeteer.launch({ headless: true });

  const clueDatabase = {};

  // Inject Sarthak
  if (!guests.some(g => g.name === 'Sarthak')) {
    guests.push({
      name: 'Sarthak',
      team: 'Startup Investors',
      role: 'Emergency Fund Liquidity Mgr',
      mission: 'Ensure no one finds out about the 18:45 emergency transfer.',
      quirk: 'Fidgets with a set of car keys while talking about money.',
      profile: 'High-level finance manager. Values numbers over people.',
      clue: 'Clue: "I moved some funds around at 18:45, but it was just for internal rebalancing. Nothing to do with the launch."\n\nCONTEXT: This transfer was actually the payout for the media silence.',
      memory: PERSONAL_MEMORIES['Sarthak']
    });
  }

  // Inject Vihan
  if (!guests.some(g => g.name === 'Vihan')) {
    guests.push({
      name: 'Vihan',
      team: 'Engineering Blackbox',
      role: 'Remote Logic Switcher',
      mission: 'Convince Engineering that the power-cycle was inevitable.',
      quirk: 'Speaks in very short, clipped sentences.',
      profile: 'Systems engineer. Believes in protocols above all else.',
      clue: 'Clue: "I saw the lock engage at 21:03 on the master board. I assumed it was an automated safety feature. I didn\'t know V was inside."\n\nCONTEXT: This lock was actually the result of the keycard revocation by Shikhar and Ayush.',
      memory: PERSONAL_MEMORIES['Vihan']
    });
  }

  // Inject The Midnight Intern
  if (!guests.some(g => g.name === 'The Midnight Intern')) {
    guests.push({
      name: 'The Midnight Intern',
      team: 'Various',
      role: 'Unpaid Narrative Intern',
      mission: 'Ask someone for sign-off on a document that doesn\'t exist.',
      quirk: 'Always carrying a cold cup of coffee and looking sleep-deprived.',
      profile: 'Underpaid and over-worked. Sees things the executives ignore.',
      clue: 'Clue: "I found a shredded paper near the printer at 8:30 PM. It had the word \'Liability\' circled."\n\nCONTEXT: This proves the board was already discussing exit strategies.',
      memory: 'You saw V and Akshat arguing in the hallway at 18:30 PM.'
    });
  }

  // Inject The IT Support
  if (!guests.some(g => g.name === 'The IT Support')) {
    guests.push({
      name: 'The IT Support',
      team: 'Various',
      role: 'Freelance Systems Auditor',
      mission: 'Check everyone\'s phone to ensure they don\'t have malware.',
      quirk: 'Fixes people\'s laptop screens without being asked.',
      profile: 'The only person who actually knows how to read the raw logs.',
      clue: 'Clue: "The server logs show a massive data wipe initiated from the VIP room at exactly 8:15 PM."\n\nCONTEXT: This wipe was the first attempt to hide the shadow deploy.',
      memory: 'You saw Kovid Poudel sweating profusely at his desk at 21:05 PM.'
    });
  }

  for (const guest of guests) {
    if (['Sajag Jain', 'Srishti Malviya', 'Padmanabhan Murli', 'Prachi Verma', 'Abhishek Mukharjee', 'Abhishek Gosavi'].includes(guest.name)) {
      console.log(`SKIPPING Generation for ABSENT/LATE guest: ${guest.name}`);
      continue;
    }
    const page = await browser.newPage();

    // Use ORIGINAL_CODES mapping if available, otherwise generate a deterministic 5-digit code
    let accessCode = ORIGINAL_CODES[guest.name] || (parseInt(crypto.createHash('sha256').update(guest.name).digest('hex').substring(0, 8), 16) % 90000 + 10000).toString();

    const hashedCode = crypto.createHash('sha256').update(accessCode).digest('hex');

    // Save to DB
    clueDatabase[hashedCode] = {
      name: Buffer.from(guest.name).toString('base64'),
      team: Buffer.from(guest.team).toString('base64'),
      clueText: Buffer.from(guest.clue).toString('base64'),
      memoryText: Buffer.from(guest.memory || 'Memory Wiped').toString('base64')
    };

    // Log the code for the master list
    console.log(`CODE_MASTER: ${guest.name} | ${accessCode}`);

    // Check which team possesses the artifact they need to ask.
    // Default sending instruction based on Team dynamics.
    let instruction = "Show your clue to NO ONE until the 8:36 PM Evidence Exchange.";
    if (guest.team === 'Startup Investors') instruction = "Ask Engineering Blackbox about the deploy logs.";
    if (guest.team === 'Engineering Blackbox') instruction = "Ask Product Council about the scope changes.";
    if (guest.team === 'Product Council') instruction = "Ask Ops & Ground Truth when V actually died.";
    if (guest.team === 'Ops & Ground Truth') instruction = "Monitor all other team claims. Catch their timeline lies.";

    const html = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,700;0,900;1,400&family=Inter:wght@300;400;600;800&family=Space+Mono:wght@400;700&display=swap" rel="stylesheet">
      <style>
        body { margin: 0; padding: 0; background: #0A0A09; color: #EFEBE1; font-family: 'Inter', sans-serif; box-sizing: border-box; }
        .wrapper { width: 1080px; padding: 80px; position: relative; }
        
        .header { text-align: center; border-bottom: 1px solid #333; padding-bottom: 40px; margin-bottom: 60px; }
        .eyebrow { font-family: 'Space Mono', monospace; color: #C9A84C; font-size: 24px; letter-spacing: 0.2em; text-transform: uppercase; margin-bottom: 20px; }
        .logo { font-family: 'Playfair Display', serif; font-weight: 900; font-size: 90px; margin: 0; line-height: 1; color: #fff; }
        .subtitle { font-family: 'Playfair Display', serif; font-style: italic; font-size: 32px; color: #7A5F28; margin-top: 20px; }

        .section-title { font-family: 'Space Mono', monospace; font-size: 30px; color: #C9A84C; margin-bottom: 25px; letter-spacing: 2px; text-transform: uppercase; border-bottom: 1px dashed #333; padding-bottom: 15px; margin-top: 60px;}

        .card { background: #141311; border: 1px solid #2A2824; border-radius: 12px; padding: 50px; margin-bottom: 20px; }
        .card-row { display: flex; justify-content: space-between; margin-bottom: 40px; }
        .card-row:last-child { margin-bottom: 0; }
        .col { width: 48%; }
        
        .label { color: #A39B8A; font-size: 20px; text-transform: uppercase; font-family: 'Space Mono', monospace; margin-bottom: 10px; }
        .value { font-size: 42px; font-weight: 800; }
        .value.highlight { color: ${TEAM_COLORS[guest.team] || '#C9A84C'}; }
        
        .bio-text { font-size: 28px; line-height: 1.5; color: #D4C4A0; border-left: 4px solid #333; padding-left: 20px; margin-top: 30px;}

        .mission-box { background: rgba(201,168,76,0.05); border: 2px solid rgba(201,168,76,0.3); border-left: 8px solid #C9A84C; padding: 40px; border-radius: 12px; margin-bottom: 30px; }
        .mission-text { font-size: 34px; line-height: 1.4; font-weight: 600; color: #fff; }

        .clue-box { background: rgba(33, 150, 243, 0.05); border: 2px solid rgba(33, 150, 243, 0.3); border-left: 8px solid #2196F3; padding: 40px; border-radius: 12px; margin-bottom: 30px; }
        .clue-text { font-size: 40px; line-height: 1.4; color: #fff; font-family: 'Space Mono', monospace; }

        .quirk-box { background: rgba(217,83,79,0.1); border: 2px solid rgba(217,83,79,0.3); padding: 40px; border-radius: 12px; text-align: center; }
        .quirk-label { color: #D9534F; font-size: 24px; font-family: 'Space Mono', monospace; font-weight: bold; margin-bottom: 15px; text-transform: uppercase; letter-spacing: 3px; }
        .quirk-text { font-size: 32px; font-weight: 600; color: #fff; }

        .team-bg { font-size: 26px; color: #A39B8A; line-height: 1.5; padding: 40px; background: #141311; border-radius: 12px; }

        .roster-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 40px; }

        .footer { text-align: center; margin-top: 80px; font-size: 24px; color: #555; font-family: 'Space Mono', monospace; }
        
        .top-secret-stamp {
          position: absolute;
          top: 100px;
          right: 40px;
          border: 6px solid #D9534F;
          color: #D9534F;
          padding: 10px 30px;
          font-size: 40px;
          font-family: 'Space Mono', monospace;
          font-weight: 700;
          transform: rotate(25deg);
          letter-spacing: 5px;
          border-radius: 10px;
        }
      </style>
    </head>
    <body>
      <div class="wrapper">
        <div class="top-secret-stamp">DIGITAL IDENTITY</div>
        
        <div class="header">
          <div class="eyebrow">READ OFF PHONE DURING GAMEPLAY</div>
          <h1 class="logo">THE GROVE INCIDENT</h1>
          <div class="subtitle">This is your complete role package. Do not share.</div>
        </div>

        <div class="card">
          <div class="card-row">
            <div class="col">
              <div class="label">Subject Identity</div>
              <div class="value">${guest.name}</div>
            </div>
            <div class="col">
              <div class="label">Assigned Role</div>
              <div class="value highlight">${guest.role.split('-')[1]?.trim() || guest.role}</div>
            </div>
          </div>
          <div class="card-row">
            <div class="col">
              <div class="label">Team / Faction</div>
              <div class="value">${guest.team}</div>
            </div>
            <div class="col">
              <div class="label">Dresscode Focus</div>
              <div class="value" style="font-size: 30px;">${TEAM_DRESSCODES[guest.team] || 'Dark mode'}</div>
            </div>
          </div>
          <div class="bio-text">
            <strong>Background:</strong> ${guest.profile}
          </div>
        </div>

        <div class="section-title">01 // Mandatory Quirk</div>
        <div class="quirk-box">
          <div class="quirk-label">Roleplay Instruction</div>
          <div class="quirk-text">"${guest.quirk}"</div>
        </div>

        <div class="section-title">02 // Your Objectives</div>
        <div class="mission-box">
          <div class="label" style="color:#C9A84C;">Primary Action:</div>
          <div class="mission-text">${guest.mission}</div>
        </div>

        <div class="section-title">03 // Encrypted Evidence Locker</div>
        <div class="clue-box">
          <div class="label" style="color:#2196F3;">Your Artifact Access Code:</div>
          <div class="clue-text" style="font-size: 60px; text-align: center; letter-spacing: 15px; margin: 30px 0; font-weight: bold;">${accessCode}</div>
          <div class="label" style="color:#2196F3;">DECRYPTION INSTRUCTIONS:</div>
          <div class="clue-text" style="font-size: 26px;">1. Go to the event website.<br>2. Open the DECRYPTION TERMINAL.<br>3. Enter your code and solve your Faction's puzzle to view your physical clue.</div>
          <div class="label" style="color:#E91E63; margin-top: 20px;">ONCE DECRYPTED, WHO TO SHOW IT TO:</div>
          <div class="clue-text" style="font-size: 22px; color: #E91E63;">${instruction}</div>
        </div>

        <div class="section-title">04 // Faction Background</div>
        <div class="team-bg">
          <strong style="color:#fff;">Your Faction's Context:</strong> ${TEAM_SUMMARIES[guest.team] || 'You are piecing together the timeline.'} <br><br>
          <strong style="color:#fff;">General Timeline:</strong> V died at 9:14 PM exactly one year ago. The technical failure started at exactly 7:03 PM. Everything in between is a blur of panic, cover-ups, and lies. Your job is to find out who made the choices that killed the company and the founder.
        </div>

        <div class="section-title">05 // The Company Roster</div>
        <div class="roster-grid">
          ${rosterHTML}
        </div>

        <div class="footer">DO NOT SHOW THIS SCREEN TO ANYONE. PLAY YOUR PART.</div>
      </div>
    </body>
    </html>
    `;

    await page.setContent(html, { waitUntil: 'networkidle0' });
    const bodyHeight = await page.evaluate(() => document.body.scrollHeight);
    await page.setViewport({ width: 1080, height: bodyHeight, deviceScaleFactor: 2 });

    const filename = guest.name.toLowerCase().replace(/[^a-z0-9]/g, '_') + '.jpg';
    await page.screenshot({ path: path.join(outDir, filename), type: 'jpeg', quality: 90, fullPage: true });

    console.log(`Generated HTML Infographic for: ${guest.name}`);
    await page.close();
  }

  await browser.close();

  // Write the database file
  fs.writeFileSync(path.join(__dirname, 'clues_database.js'), 'const CLUE_DB = ' + JSON.stringify(clueDatabase, null, 2) + ';');

  console.log('All ULTIMATE infographics generated successfully in /ultimate_posters!');
  console.log('Created clues_database.js with all access codes.');
}

generateHTMLPosters().catch(console.error);
